indent-width = 4

select = [
  "F",
  "W6",
  "E71",
  "E72",
  "E112",
  "E113",
  "E203",
  "E272",
  "E501",
  "E702",
  "E703",
  "E731",
  "W191",
  "W291",
  "W293",
  "UP039",  # unnecessary-class-parentheses
]

line-length = 150
