pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true
    architecture: 'x64'

- script: |
    python -m pip install pipenv
    python -m pipenv install --dev
  displayName: 'Setup Python environment'

- script: |
    sh run.linter.sh
  displayName: 'Run mypy Lint'
