trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo apt-get update --allow-releaseinfo-change && sudo apt-get install -y ghostscript'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true
    architecture: 'x64'

- script: |
    python -m pip install pipenv
    python -m pipenv install --dev
  displayName: 'Setup environment'

- script: |
    sh run.tests.sh
  displayName: 'Run unit tests'
