name: Test CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ghostscript
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: Install pipenv
        run:
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run:
          pipenv install --dev --deploy

      - name: Check linting
        run: |
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          pipenv run flake8 . --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics

      - name: Check type hinting with mypy
        run: |
          pipenv run mypy hotpdf/ --strict
          pipenv run mypy tests/ --check-untyped-defs

      - name: Run tests with coverage
        run: |
          pipenv run coverage run --omit="*/test*" -m pytest tests/
          pipenv run coverage report --fail-under=100